### ISSUE TITLE
code threatening me???

### ISSUE THREAD

**Issue by snailmusic** [Narwaffle22/df-your-mom#6]
when i open the program at 11:59am it just opens a window saying "brb going to ur moms house ur gonna have another brother"
but like my mom is dead????
# help
#5 @subby2006 @Narwaffle22

**Comment by Narwaffle22** [comment]
sounds like a skill issue

**Comment by snailmusic** [comment]
fixed

**Comment by snailmusic** [comment]
> sounds like a skill issue

pog
